### ISSUE TITLE
Push new version to NuGet

### ISSUE THREAD

**Issue by tomgrowflow** [ryanjerskine/LaunchDarkly.Api#2]
Can you push a new version to NuGet that includes this commit?

https://github.com/ryanjerskine/LaunchDarkly.Api/commit/0c827e5b9418e1a024e9e80760b4ca83ccbf2d2e

This commit was made 9 months ago, and nuget version is from 2 years ago.

**Comment by ryanjerskine** [comment]
New version is pushed: https://www.nuget.org/packages/LaunchDarkly.Api/3.6.1. Thanks again for the work on this, feel free to open another issue if you have any problems.
